"""Initial migration

Revision ID: c269b7c6131a
Revises: 
Create Date: 2025-07-20 10:24:43.227791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c269b7c6131a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cours_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'cours', ['cours_id'], ['id'])
        # batch_op.drop_column('justifie')
        # batch_op.drop_column('commentaire')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commentaire', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('justifie', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('notes')
        batch_op.drop_column('cours_id')

    # ### end Alembic commands ###
